# --- General ---
set -g prefix M-s               # Set prefix to Alt+s
unbind C-b                      # Unbind the default prefix
bind M-s send-prefix            # Allow sending prefix if pressed twice

# Start window/session numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# No status line at all
set -g status off

# --- Splits ---
# Horizontal split: 
bind - split-window -v

# Vertical split: 
bind v split-window -h

# --- Pane navigation (like Neovim) ---
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# --- Quality of life ---
setw -g mouse on                # Mouse is basically for scrolling while reading logs, kind of mandatory 
bind r source-file ~/.tmux.conf \; display "Reloaded tmux.conf"
# -- Removing comfirmation for removing panes by rebiding kill-pane 
unbind x
bind x kill-pane
bind n new-session 

