
# preload = /home/vlad/Pictures/mountain_black.jpg
#
# wallpaper = eDP-1,/home/vlad/Pictures/mountain_black.jpg
#
# ipc = off

wallpaper {
    monitor = eDP-1
    path = /home/vlad/Pictures/wallpapers/wallhaven-g75wvd.jpg
    fit_mode = cover
}

splash = false
ipc = off
